name: Prettier Action
description: Automatically runs prettier on all your changes.

author: Johannes Korbmacher (j.korbmacher@uu.nl)

inputs:
  prettier_options:
    description: Options for the `prettier` command
    required: false
    default: '--write public/'
  dry:
    description: Running the script in dry mode just shows whether there are files that should be prettified or not
    required: false
    default: false
  prettier_version:
    description: Specific version of prettier (by default just use the latest version)
    required: false
    default: false
  prettier_plugins:
    description: Install Prettier plugins, i.e. `@prettier/prettier-php @prettier/some-other-plugin`
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
